name: 'Auto Assign'

inputs:
  token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: true
  configuration:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'

runs:
  using: "composite"
  steps:
    - name: Transfer to S3 for Serving Api-Server
      uses: actions/setup-python@v4
      with:
      python-version: ${{ matrix.python-version }}

    - name: Test
      env:
        TOKEN : ${{ inputs.token }}
      run: python main.py

