name: 'Auto Assign'

inputs:
  token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: true
  configuration:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'

runs:
  using: "composite"
  steps:
    - name: Transfer to S3 for Serving Api-Server
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Test
      env:
        TOKEN: ${{ inputs.token }}
      shell: bash
      run: ls -al

    - name: Test
      env:
        TOKEN: ${{ inputs.token }}
      shell: bash
      run: ls -al /home/runner/work/auto_assign_test

    - name: Test
      env:
        TOKEN : ${{ inputs.token }}
      shell: bash
      run: python ../main.py

