name: 'Auto Assign Reviewers'

inputs:
  token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: true
  reviewers:
    description: 'Reviewers(comma separated list)'
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'nhjeon/auto-assign'
        ref: 'main'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependency
      shell: bash
      run: pip install PyGithub
    - name: Add Reviewers
      env:
        TOKEN : ${{ inputs.token }}
        REVIEWERS : ${{ inputs.reviewers }}
      shell: bash
      run: python app/main.py

