name: 'Auto Assign'

inputs:
  token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: true
  configuration:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'nhjeon/auto-assign'
        ref: 'main'
    - name: Transfer to S3 for Serving Api-Server
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Test
      shell: bash
      run: pip install PyGithub
    - name : Test
      shell: |
          curl --request GET \
          --url "https://api.github.com/octocat" \
          --header "Authorization: Bearer $GH_TOKEN"
    - name: Test
      env:
        TOKEN : ${{ inputs.token }}
      shell: bash
      run: python app/main.py

