name: 'Auto Assign'

inputs:
  token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: true
  configuration:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.configuration }}
